### ISSUE TITLE
Remove Rails and the rail mountings on boxes

### ISSUE THREAD

**Issue by Danyc0** [abersailbot/kitty-hardware#13]
Sorry @kragniz but they make it SO much harder to get the boxes in and out

**Comment by kragniz** [comment]
RIP our advanced technology: https://www.youtube.com/watch?v=4pei8jrFM2A
:shipit:

**Comment by CloudCoppola** [comment]
Rails and rail mounts on main big box have been removed - issue fixed
Are there other boxes?

**Comment by Danyc0** [comment]
:'( end of an era :P
