### ISSUE TITLE
Ensuring all wiring follows the wiring standard

### ISSUE THREAD

**Issue by Danyc0** [abersailbot/kitty-hardware#21]
There is a wiring standard in the Management repository which should be followed: https://github.com/abersailbot/management/blob/master/sailbot-wiring-standard.md

**Comment by Danyc0** [comment]
See comments on the issue in dewi-hardware: abersailbot/dewi-hardware#40

**Comment by ghost** [comment]
Kitty should be getting a total rewire, so we can get it to spec then

**Comment by Danyc0** [comment]
Why has this been closed despite not being completed?
