### ISSUE TITLE
Secure compass

### ISSUE THREAD

**Issue by JSpringett** [abersailbot/kitty-hardware#5]

**Comment by Danyc0** [comment]
Please make sure it's an HMC6343, the CMPS10's caused us so much hassle in San Francisco 2014. (Although there is now a CMPS11 which should probably be investigated and TOUGHLY TESTED)

**Comment by MFrankland** [comment]
The compass is attached but not quite secure, my hands are too large to properly tighten the screws

**Comment by adaszymczak** [comment]
Screws has been changed - issue fixed
